- city: Abu Dhabi
  country: Emirados Árabes Unidos
- city: Abuja
  country: Nigéria
- city: Acra
  country: Gana
- city: Adamstown
  country: Pitcairn
- city: Adis Abeba
  country: Etiópia
- city: Agana
  country: Guam
- city: Alofi
  country: Niue
- city: Amã
  country: Jordânia
- city: Amsterdã
  country: Países Baixos
- city: Ancara
  country: Turquia
- city: Andorra-a-Velha
  country: Andorra
- city: Antananarivo
  country: Madagáscar
- city: Apia
  country: Samoa
- city: Argel
  country: Argélia
- city: Asgabate
  country: Turquemenistão
- city: Asmara
  country: Eritreia
- city: Assunção
  country: Paraguai
- city: Astana
  country: Cazaquistão
- city: Atenas
  country: Grécia
- city: Avarua
  country: Ilhas Cook
- city: Baku
  country: Azerbaijão
- city: Bagdá
  country: Iraque
- city: Bamako
  country: Mali
- city: Bandar Seri Begawan
  country: Brunei
- city: Banguecoque
  country: Tailândia
- city: Bangui
  country: República Centro-Africana
- city: Banjul
  country: Gâmbia
- city: Basse-Terre
  country: Guadalupe
- city: Basseterre
  country: São Cristóvão e Nevis
- city: Beirute
  country: Líbano
- city: Belfast
  country: Irlanda do Norte
- city: Belgrado
  country: Sérvia
- city: Belmopan
  country: Belize
- city: Berlim
  country: Alemanha
- city: Berna
  country: Suíça
- city: Bisqueque
  country: Quirguistão
- city: Bissau
  country: Guiné-Bissau
- city: Bogotá
  country: Colômbia
- city: Brades Estate
  country: Montserrat
- city: Brasília
  country: Brasil
- city: Bratislava
  country: Eslováquia
- city: Brazzaville
  country: República do Congo
- city: Bridgetown
  country: Barbados
- city: Bruxelas
  country: Bélgica
- city: Bucareste
  country: Roménia
- city: Budapeste
  country: Hungria
- city: Buenos Aires
  country: Argentina
- city: Bujumbura
  country: Burundi
- city: Cabul
  country: Afeganistão
- city: Caiena
  country: Guiana Francesa
- city: Cairo
  country: Egito
- city: Camberra
  country: Austrália
- city: Campala
  country: Uganda
- city: Caracas
  country: Venezuela
- city: Cardiff
  country: País de Gales
- city: Charlotte Amalie
  country: Ilhas Virgens Americanas
- city: Cartum
  country: Sudão
- city: Castries
  country: Santa Lúcia
- city: Catmandu
  country: Nepal
- city: Chişinău
  country: Moldávia
- city: Cidade do Cabo
  country: África do Sul
- city: Cidade da Guatemala
  country: Guatemala
- city: Cidade do México
  country: México
- city: Panamá
  country: Panamá
- city: Cingapura
  country: Singapura
- city: Cockburn Town
  country: Turcas e Caicos
- city: Colombo
  country: Sri Lanka
- city: Conacri
  country: Guiné
- city: Copenhague
  country: Dinamarca
- city: Cotonou
  country: Benim
- city: Dakar
  country: Senegal
- city: Daca
  country: Bangladesh
- city: Damasco
  country: Síria
- city: Dar-es-Salaam
  country: Tanzânia
- city: Díli
  country: Timor-Leste
- city: Djibouti
  country: Djibouti
- city: Doha
  country: Catar
- city: Douglas
  country: Ilha de Man
- city: Dublim
  country: Irlanda
- city: Dushanbe
  country: Tadjiquistão
- city: Estocolmo
  country: Suécia
- city: El Aaiún
  country: Saara Ocidental
- city: Edimburgo
  country: Escócia
- city: Flying Fish Cove
  country: Ilha do Natal
- city: Fort-de-France
  country: Martinica
- city: Freetown
  country: Serra Leoa
- city: Funafuti
  country: Tuvalu
- city: Gaborone
  country: Botswana
- city: Gaza
  country: Faixa de Gaza
- city: George Town
  country: Ilhas Cayman
- city: Georgetown
  country: Guiana
- city: Gibraltar
  country: Gibraltar
- city: Grytviken
  country: Ilhas Geórgia do Sul e Sandwich do Sul
- city: Hamilton
  country: Bermudas
- city: Hanói
  country: Vietname
- city: Harare
  country: Zimbabwe
- city: Havana
  country: Cuba
- city: Helsinque
  country: Finlândia
- city: Honiara
  country: Ilhas Salomão
- city: Ierevan
  country: Arménia
- city: Islamabad
  country: Paquistão
- city: Jacarta
  country: Indonésia
- city: Jamestown
  country: Santa Helena, Ascensão e Tristão da Cunha
- city: Jerusalém
  country: Israel e Palestina
- city: Juba
  country: Sudão do Sul
- city: Kiev
  country: Ucrânia
- city: Kigali
  country: Ruanda
- city: Kingston
  country: Jamaica
- city: Kingston
  country: Ilha Norfolk
- city: Kingstown
  country: São Vicente e Granadinas
- city: Kinshasa
  country: República Democrática do Congo
- city: Kuala Lumpur
  country: Malásia
- city: Kuwait
  country: Kuwait
- city: La Paz
  country: Bolívia
- city: Lassa
  country: Tibete
- city: Libreville
  country: Gabão
- city: Lilongwe
  country: Malawi
- city: Lima
  country: Peru
- city: Lisboa
  country: Portugal
- city: Liubliana
  country: Eslovênia
- city: Lomé
  country: Togo
- city: Londres
  country: Inglaterra
- city: Longyearbyen
  country: Svalbard e Jan Mayen
- city: Luanda
  country: Angola
- city: Lusaka
  country: Zâmbia
- city: Luxemburgo
  country: Luxemburgo
- city: Madrid
  country: Espanha
- city: Majuro
  country: Ilhas Marshall
- city: Malabo
  country: Guiné Equatorial
- city: Malé
  country: Maldivas
- city: Mamudzu
  country: Maiote
- city: Manágua
  country: Nicarágua
- city: Manama
  country: Bahrein
- city: Manila
  country: Filipinas
- city: Maputo
  country: Moçambique
- city: Mariehamn
  country: Ilhas Åland
- city: Mascate
  country: Omã
- city: Maseru
  country: Lesoto
- city: Mata-Utu
  country: Wallis e Futuna
- city: Mbabane
  country: Suazilândia
- city: Minsk
  country: Bielorrússia
- city: Mogadíscio
  country: Somália
- city: Mónaco-Cidade
  country: Mónaco
- city: Monróvia
  country: Libéria
- city: Montevideu
  country: Uruguai
- city: Moroni
  country: Comores
- city: Moscou
  country: Rússia
- city: Nairobi
  country: Quênia
- city: Nassau
  country: Bahamas
- city: Naipidau
  country: Myanmar
- city: Jamena
  country: Chade
- city: Ngerulmud
  country: Palau
- city: Niamey
  country: Níger
- city: Nicósia
  country: Chipre
- city: Nouakchott
  country: Mauritânia
- city: Nouméa
  country: Nova Caledônia
- city: Nova Deli
  country: Índia
- city: Nuku alofa
  country: Tonga
- city: Nuuk
  country: Gronelândia
- city: Oranjestad
  country: Aruba
- city: Oslo
  country: Noruega
- city: Ottawa
  country: Canadá
- city: Ouagadougou
  country: Burkina Faso
- city: Pago Pago
  country: Samoa Americana
- city: Palikir
  country: Estados Federados da Micronésia
- city: Papeete
  country: Polinésia Francesa
- city: Paramaribo
  country: Suriname
- city: Paris
  country: França
- city: Phnom Penh
  country: Camboja
- city: Pequim
  country: China
- city: Pyongyang
  country: Coreia do Norte
- city: Plymout
  country: Montserrat
- city: Podgorica
  country: Montenegro
- city: Porto de Espanha
  country: Trinidad e Tobago
- city: Porto Príncipe
  country: Haiti
- city: Porto Luís
  country: Maurícia
- city: Porto Moresby
  country: Papua-Nova Guiné
- city: Port Vila
  country: Vanuatu
- city: Porto-Novo
  country: Benim
- city: Praga
  country: República Checa
- city: Praia
  country: Cabo Verde
- city: Pristina
  country: Kosovo
- city: Quito
  country: Equador
- city: Rabat
  country: Marrocos
- city: Reykjavik
  country: Islândia
- city: Riade
  country: Arábia Saudita
- city: Riga
  country: Letônia
- city: Road Town
  country: Ilhas Virgens Britânicas
- city: Roma
  country: Itália
- city: Roseau
  country: Dominica
- city: Saint-Denis
  country: Reunião
- city: Saint George
  country: Granada
- city: Saint Helier
  country: Jersey
- city: Saint John
  country: Antígua e Barbuda
- city: São Pedro
  country: São Pedro e Miquelão
- city: Saipão
  country: Marianas Setentrionais
- city: San José
  country: Costa Rica
- city: San Juan
  country: Porto Rico
- city: San Salvador
  country: El Salvador
- city: Saná
  country: Iémen
- city: Santiago do Chile
  country: Chile
- city: São Domingos
  country: República Dominicana
- city: San Marino
  country: São Marino
- city: São Tomé
  country: São Tomé e Príncipe
- city: Saraievo
  country: Bósnia e Herzegovina
- city: Seul
  country: Coreia do Sul
- city: Skopje
  country: Macedónia
- city: Sófia
  country: Bulgária
- city: Stanley
  country: Ilhas Malvinas
- city: Saint Peter Port
  country: Guernesei
- city: Suva
  country: Fiji
- city: Taipé
  country: Taiwan
- city: Tallinn
  country: Estónia
- city: Tarawa do Sul
  country: Kiribati
- city: Tashkent
  country: Uzbequistão
- city: Tbilissi
  country: Geórgia
- city: Teerã
  country: Irã
- city: Tegucigalpa
  country: Honduras
- city: Thimphu
  country: Butão
- city: Tirana
  country: Albânia
- city: Tóquio
  country: Japão
- city: Tórshavn
  country: Ilhas Feroé
- city: Trípoli
  country: Líbia
- city: Túnis
  country: Tunísia
- city: Ulan Bator
  country: Mongólia
- city: Vaduz
  country: Liechtenstein
- city: Valeta
  country: Malta
- city: The Valley
  country: Anguilla
- city: Varsóvia
  country: Polónia
- city: Vaticano
  country: Vaticano
- city: Vitória
  country: Seychelles
- city: Viena
  country: Áustria
- city: Vientiane
  country: Laos
- city: Vilna
  country: Lituânia
- city: Washington, DC
  country: Estados Unidos
- city: Wellington
  country: Nova Zelândia
- city: West Island
  country: Ilhas Cocos
- city: Willemstad
  country: Antilhas Holandesas
- city: Windhoek
  country: Namíbia
- city: Yamoussoukro
  country: Costa do Marfim
- city: Yaoundé
  country: Camarões
- city: Yaren
  country: Nauru
- city: Zagreb
  country: Croácia

