# encoding: UTF-8
- name: Homem é morto por Sabre de Luz durante corrida
  description: O crime ocorreu %%yesterday%% durante a corrida de pods em %%city%%, %%country%%. A vitima, identificada apenas como Luke, faleceu antes da chegada dos médicos. A Polícia Imperial foi chamada, mas o suspeito já havia fugido.

- name: Um Anel é roubado a caminho de Mordor
  description: Golum, o último proprietário do Anel, afirma que a jóia foi roubada em %%city%%, %%country%%. A polícia e Sauron procuram pistas sobre o ladrão.

- name: Wally está desaparecido
  description: Testemunhas afirmam que um suspeito rondava a casa de Wally em %%city%%, %%country%% poucos dias antes do desparecimento. Após multiplas buscas feitas nos livros da série, o seu paradeiro ainda é desconhecido. A polícia se pergunta onde estará Wally.

- name: Senhor Cabeça de Batata é sequestrado
  description: A vítima foi sequestrada na noite de %%yesterday%% quanto voltava para casa em %%city%%, %%country%%. Autoridades afirmam que o sequestrador pediu resgate de R$ 1 milhão e enviou como prova a orelha do Senhor Cabeça de Batata.

