# encoding: UTF-8
male:
 - Adão
 - Alexandre
 - André
 - Antônio
 - Augusto
 - Carlos
 - César
 - Cláudio
 - Daniel
 - Eduardo
 - Fábio
 - Felipe
 - Fernando
 - Francisco
 - Gilberto
 - Guilherme
 - Gustavo
 - Henrique
 - João
 - Jorge
 - José
 - Júlio
 - Leonardo
 - Luciano
 - Luis
 - Manoel
 - Marcelo
 - Márcio
 - Marcos
 - Mário
 - Paulo
 - Pedro
 - Rafael
 - Renato
 - Ricardo
 - Roberto
 - Rodrigo
 - Rogério
 - Sérgio
 - Tiago

female:
 - Adriana
 - Ana
 - Andréa
 - Beatriz
 - Carla
 - Carmem
 - Carolina
 - Cláudia
 - Cristina
 - Denise
 - Elisabete
 - Eva
 - Fátima
 - Fernanda
 - Helena
 - Inês
 - Isabel
 - Lourdes
 - Lúcia
 - Luciana
 - Luiza
 - Mara
 - Márcia
 - Maria
 - Marilin/e
 - Marisa
 - Marlene
 - Marli
 - Patrícia
 - Paula
 - Regina
 - Rosa
 - Rosana
 - Sandra
 - Simone
 - Sônia
 - Tânia
 - Tereza
 - Terezinha
 - Vera

